name: "Code Coverage Report"
description: "Comments a pull request with the code coverage"
author: "Romeo Van Snick"
branding:
  icon: "check-square"
  color: "green"
inputs:
  github-token:
    description: "Github token"
    required: true
	lcov-file:
    description: "The location of the lcov.info file"
    required: false
runs:
  using: "node12"
  main: "index.js"
